stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

before_script:
  - echo "Before script running..."
  - ls -al node_modules || echo "node_modules not found"
  - apt-get update -y
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install
  - export PATH="./node_modules/.bin:$PATH"

build:
  stage: build
  script:
    - echo "Building the project..."
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo $TESTVARIABLE
    #- npm test
  artifacts:
    reports:
      junit: junit.xml

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
