stages:
  - build
  - test
  - deploy

#variables:
  #NODE_ENV: 'development'
  #FIREBASE_TOKEN: $FIREBASE_TOKEN

before_script:
  - apt-get update -y
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install
  - export PATH="./node_modules/.bin:$PATH"

build:
  stage: build
  script:
    - echo "Building the project..."
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - echo "Running tests..."
    #- npm test
  artifacts:
    reports:
      junit: junit.xml

deploy:
  stage: deploy
  script:
    - echo "Deploying to Firebase..."
    - npm install -g firebase-tools
    #- firebase deploy --token $FIREBASE_TOKEN

